import { useState, type FormEvent } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthProvider'

export function AuthPage() {
  const login = useLocation().pathname === '/login'; const nav = useNavigate(); const auth = useAuth()
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [otp,setOtp]=useState(''); const [challengeId,setChallengeId]=useState<string>(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { if (login) { await auth.login(email,password); nav('/candidate') } else if (challengeId) { await auth.verifyRegistration(challengeId,otp); nav('/login') } else { const challenge=await auth.register(name,email,password); setChallengeId(challenge.challengeId) } } catch (exception) { setError(exception instanceof Error ? exception.message : 'Request failed.') } finally { setBusy(false) } }
  const title = login ? 'Welcome back.' : challengeId ? 'Verify your email.' : 'Start something new.'
  return <section className="auth-page"><div><p className="eyebrow">YUNXIAOJOB</p><h1>{title}</h1><p>{challengeId ? `We sent a 6-digit code to ${email}. It expires in 5 minutes.` : login ? 'Sign in to continue your job search.' : 'Create a free account in just a few minutes.'}</p></div><form className="auth-card" onSubmit={submit}><h2>{login?'Sign in':challengeId?'Email verification':'Create account'}</h2>{!login&&!challengeId&&<><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></>}{login&&<><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></>}{challengeId&&<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value)} placeholder="6-digit OTP"/>}{error&&<p className="form-error">{error}</p>}<button className="button" disabled={busy}>{busy?'Processing…':challengeId?'Verify OTP →':login?'Sign in →':'Send OTP →'}</button>{!challengeId&&<p>{login?'No account yet?':'Already have an account?'} <Link to={login?'/register':'/login'}>{login?'Register':'Sign in'}</Link></p>}</form></section>
}
