using YunXiaoJob.Application.DTOs.Responses;
using YunXiaoJob.Application.Interfaces;
using YunXiaoJob.Application.Interfaces.Repositories;
using YunXiaoJob.Application.UseCases.Queries;
using YunXiaoJob.Domain.Entities;
using YunXiaoJob.Domain.Enums;
namespace YunXiaoJob.Application.UseCases.Candidates;
public sealed class SaveJobUseCase { private readonly ICandidateRepository _candidates; private readonly IJobPostingRepository _jobs; private readonly ICompanyRepository _companies; private readonly IUnitOfWork _unit; public SaveJobUseCase(ICandidateRepository candidates,IJobPostingRepository jobs,ICompanyRepository companies,IUnitOfWork unit){_candidates=candidates;_jobs=jobs;_companies=companies;_unit=unit;} public async Task ExecuteAsync(Guid jobId,Guid userId,CancellationToken ct=default){var p=await _candidates.GetProfileByUserIdAsync(userId,cancellationToken:ct)??throw new KeyNotFoundException("Candidate profile was not found.");var j=await _jobs.GetByIdAsync(jobId,cancellationToken:ct)??throw new KeyNotFoundException("Job posting was not found.");var c=await _companies.GetByIdAsync(j.CompanyId,cancellationToken:ct)??throw new KeyNotFoundException("Company was not found.");if(j.Status!=JobPostingStatus.Published||c.Status!=CompanyStatus.Active||(j.ApplicationDeadline is not null&&j.ApplicationDeadline<DateOnly.FromDateTime(DateTime.UtcNow)))throw new InvalidOperationException("Only an open job can be saved.");if(await _candidates.GetSavedJobAsync(p.Id,j.Id,ct) is null){await _candidates.AddSavedJobAsync(new SavedJob{CandidateProfileId=p.Id,JobPostingId=j.Id},ct);await _unit.SaveChangesAsync(ct);}} }
public sealed class RemoveSavedJobUseCase { private readonly ICandidateRepository _candidates; private readonly IUnitOfWork _unit; public RemoveSavedJobUseCase(ICandidateRepository candidates,IUnitOfWork unit){_candidates=candidates;_unit=unit;} public async Task ExecuteAsync(Guid jobId,Guid userId,CancellationToken ct=default){var p=await _candidates.GetProfileByUserIdAsync(userId,cancellationToken:ct)??throw new KeyNotFoundException("Candidate profile was not found.");var saved=await _candidates.GetSavedJobAsync(p.Id,jobId,ct)??throw new KeyNotFoundException("Saved job was not found.");_candidates.RemoveSavedJob(saved);await _unit.SaveChangesAsync(ct);} }
public sealed class GetSavedJobsUseCase { private readonly ICandidateRepository _candidates; private readonly IJobPostingRepository _jobs; private readonly ICompanyRepository _companies; public GetSavedJobsUseCase(ICandidateRepository candidates,IJobPostingRepository jobs,ICompanyRepository companies){_candidates=candidates;_jobs=jobs;_companies=companies;} public async Task<IReadOnlyList<JobPostingSummaryResponse>> ExecuteAsync(Guid userId,CancellationToken ct=default){var p=await _candidates.GetProfileByUserIdAsync(userId,cancellationToken:ct)??throw new KeyNotFoundException("Candidate profile was not found.");var ids=(await _candidates.GetSavedJobsAsync(p.Id,ct)).Select(x=>x.JobPostingId).ToList();var jobs=await _jobs.GetByIdsAsync(ids,ct);var companies=(await _companies.GetByIdsAsync(jobs.Select(x=>x.CompanyId).Distinct().ToList(),ct)).ToDictionary(x=>x.Id);return jobs.Where(x=>x.Status==JobPostingStatus.Published&&companies.GetValueOrDefault(x.CompanyId)?.Status==CompanyStatus.Active).Select(x=>x.ToSummary(companies[x.CompanyId])).ToList();} }
