using YunXiaoJob.Application.DTOs.Responses;
using YunXiaoJob.Application.Interfaces;
using YunXiaoJob.Application.Interfaces.Repositories;
using YunXiaoJob.Application.UseCases.Queries;
using YunXiaoJob.Domain.Enums;
namespace YunXiaoJob.Application.UseCases.Administration;
public sealed class RejectJobPostingUseCase { private readonly IUserRepository _users; private readonly IJobPostingRepository _jobs; private readonly IUnitOfWork _unit; public RejectJobPostingUseCase(IUserRepository users,IJobPostingRepository jobs,IUnitOfWork unit){_users=users;_jobs=jobs;_unit=unit;} public async Task<JobPostingResponse> ExecuteAsync(Guid id,Guid userId,CancellationToken ct=default){var admin=await _users.GetByIdAsync(userId,ct);if(admin?.PlatformRole!=PlatformRole.Admin)throw new UnauthorizedAccessException();var job=await _jobs.GetByIdAsync(id,true,ct)??throw new KeyNotFoundException("Job posting was not found.");if(job.Status!=JobPostingStatus.PendingApproval)throw new InvalidOperationException("Only submitted postings can be rejected.");job.Status=JobPostingStatus.Rejected;job.UpdatedAtUtc=DateTime.UtcNow;await _unit.SaveChangesAsync(ct);return job.ToResponse();} }
public sealed class SuspendCompanyUseCase { private readonly IUserRepository _users; private readonly ICompanyRepository _companies; private readonly IUnitOfWork _unit; public SuspendCompanyUseCase(IUserRepository users,ICompanyRepository companies,IUnitOfWork unit){_users=users;_companies=companies;_unit=unit;} public async Task<CompanyResponse> ExecuteAsync(Guid id,Guid userId,CancellationToken ct=default){var admin=await _users.GetByIdAsync(userId,ct);if(admin?.PlatformRole!=PlatformRole.Admin)throw new UnauthorizedAccessException();var company=await _companies.GetByIdAsync(id,cancellationToken:ct)??throw new KeyNotFoundException("Company was not found.");if(company.Status!=CompanyStatus.Active)throw new InvalidOperationException("Only an active company can be suspended.");company.Status=CompanyStatus.Suspended;company.UpdatedAtUtc=DateTime.UtcNow;await _unit.SaveChangesAsync(ct);return company.ToResponse();} }
public sealed class RejectCompanyUseCase { private readonly IUserRepository _users; private readonly ICompanyRepository _companies; private readonly IUnitOfWork _unit; public RejectCompanyUseCase(IUserRepository users,ICompanyRepository companies,IUnitOfWork unit){_users=users;_companies=companies;_unit=unit;} public async Task<CompanyResponse> ExecuteAsync(Guid id,Guid userId,CancellationToken ct=default){var admin=await _users.GetByIdAsync(userId,ct);if(admin?.PlatformRole!=PlatformRole.Admin)throw new UnauthorizedAccessException();var company=await _companies.GetByIdAsync(id,cancellationToken:ct)??throw new KeyNotFoundException("Company was not found.");if(company.Status!=CompanyStatus.PendingVerification)throw new InvalidOperationException("Only a pending company can be rejected.");company.Status=CompanyStatus.Rejected;company.UpdatedAtUtc=DateTime.UtcNow;await _unit.SaveChangesAsync(ct);return company.ToResponse();} }
